inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
    - node_modules/**/*

Style/Documentation:
  Exclude:
    - db/migrate/*
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/application.rb

Style/MixinUsage:
  Exclude:
    - bin/*

Metrics/BlockLength:
  ExcludedMethods:
    - setup
  Exclude:
    - config/routes.rb
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/LineLength:
  Max: 120
  Exclude:
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
