services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
      - NODE_ENV=development
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    # To allow yarn --watch from Procfile.dev to continue after stdin is closed
    tty: true
  sidekiq:
    build: .
    command: sidekiq
    environment:
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
volumes:
  postgres-data:
  node_modules:
