version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
     # No ports shared externally, so that this doesn't conflict with the postgres
     # server that TravisCI starts up.
     # ports:
     #   - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
