version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.2.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
      - ruby-rails/test-rails:
          name: test
          executor:
            name: ruby-rails/ruby-postgres
            ruby-tag: '3.2.2'
          install-chrome: true
          before-test:
            - run:
                name: compile assets
                command: bundle exec rails test:prepare
