version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@2.0.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
      - ruby-rails/test-rails:
          name: test
          before-test:
            - run:
                name: compile assets
                command: bundle exec rails test:prepare
