=begin
#WASAPI Export API as implemented by Archive-It

#WASAPI Export API.  What Archive-It has implemented. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::FormDataFunction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FormDataFunction' do
  before do
    # run before each test
    @instance = OpenapiClient::FormDataFunction.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FormDataFunction' do
    it 'should create an instance of FormDataFunction' do
      expect(@instance).to be_instance_of(OpenapiClient::FormDataFunction)
    end
  end
end
