# Default number of months to embargo a collection
default_embargo_months: 6
crawl_directory: /was_unaccessioned_data/jobs
wasapi_downloader_bin: wasapi-downloader/v1.0.0/bin/wasapi-downloader

workflow:
  url: 'http://localhost:3001'

dor_services:
  url:  'https://dor-services-test.stanford.test'
  token: secret-token

argo_view_url: https://argo.stanford.edu/view/%s

validate_collection_druid: true
validate_job_directory: true
validate_source_id: true

# checkin keys for honeybadger (actual keys are in shared_configs per environment as needed)
# see https://app.honeybadger.io/projects/63547/check_ins
honeybadger_checkins:
  fetch_collections: null
