=begin
#WASAPI Export API as implemented by Archive-It

#WASAPI Export API.  What Archive-It has implemented. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for jobs_get
  # What jobs do I have?
  # Show the jobs on this server accessible to the client
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page One-based index for pagination 
  # @return [InlineResponse200]
  describe 'jobs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for jobs_jobtoken_get
  # How is my job doing?
  # Retrieve information about a job, both the parameters of its submission and its current state.  If the job is complete, the client can get the result through a separate request to &#x60;jobs/{jobtoken}/result&#x60;.
  # @param jobtoken The job token returned from previous request
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'jobs_jobtoken_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for jobs_jobtoken_result_get
  # What is the result of my job?
  # For a complete job, produces a page of the resulting files. 
  # @param jobtoken The job token returned from previous request
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page One-based index for pagination 
  # @return [FileSet]
  describe 'jobs_jobtoken_result_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for jobs_post
  # Make a new job
  # Create a job to perform some task
  # @param unknown_base_type 
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'jobs_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webdata_get
  # Get the archive files I need
  # Produces a page of the list of the files accessible to the client matching all of the parameters.  A parameter with multiple options matches when any option matches; a missing parameter implicitly matches. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page One-based index for pagination 
  # @option opts [String] :filename A string exactly matching the webdata file&#39;s basename (ie must match the beginning and end of the filename, not the full path of directories). 
  # @option opts [DateTime] :crawl_time_after Match resources that were crawled at or after the time given according to RFC3339.  A date given with no time of day means midnight.  Coordinated Universal (UTC) is preferrred and assumed if no timezone is included. Because &#x60;crawl-time-after&#x60; matches equal time stamps while &#x60;crawl-time-before&#x60; excludes equal time stamps, and because we specify instants rather than durations implicit from our units, we can smoothly scale between days and seconds.  That is, we specify ranges in the manner of the C programming language, eg low ≤ x &lt; high.  For example, matching the month of November of 2016 is specified by &#x60;crawl-time-after&#x3D;2016-11 &amp; crawl-time-before&#x3D;2016-12&#x60; or equivalently by &#x60;crawl-time-after&#x3D;2016-11-01T00:00:00Z &amp; crawl-time-before&#x3D;2016-11-30T16:00:00-08:00&#x60;. 
  # @option opts [DateTime] :crawl_time_before Match resources that were crawled strictly before the time given according to RFC3339.  See more detail at &#x60;crawl-time-after&#x60;. 
  # @option opts [DateTime] :crawl_start_after Match resources that were crawled in a job that started at or after the time given according to RFC3339.  (Note that the original content of a file could be crawled many days after the crawl job started; would you prefer &#x60;crawl-time-after&#x60; / &#x60;crawl-time-before&#x60;?) 
  # @option opts [DateTime] :crawl_start_before Match resources that were crawled in a job that started strictly before the time given according to RFC3339.  See more detail at &#x60;crawl-start-after&#x60;. 
  # @option opts [Integer] :collection The numeric ID of one or more collections, given as separate fields. For only this parameter, WASAPI accepts multiple values and will match items in any of the specified collections.  For example, matching the items from two collections can be specified by &#x60;collection&#x3D;1 &amp; collection&#x3D;2&#x60;. 
  # @option opts [Integer] :crawl The numeric ID of the crawl 
  # @return [FileSet]
  describe 'webdata_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
