wasapi_providers:
  ait:
    name: Archive-It
    baseurl: https://archive-it.org/
    authurl: https://archive-it.org/login
    accounts:
      ua:
        username: user
        password: pass
      history:
        username: user2
        password: pass2
  notait:
    name: Not Archive-It
    baseurl: https://not-archive-it.org/
    authurl: https://not-archive-it.org/login
    accounts:
      ua:
        username: user
        password: pass
crawl_directory: spec/fixtures/jobs
validate_collection_druid: false
validate_job_directory: false
validate_source_id: false